# Generated by Django 4.2.7 on 2023-12-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='subject',
            new_name='message',
        ),
    ]
